from django.urls import path
from . import views
urlpatterns=[
 path("dashboard/",views.dashboard,name="dashboard"),path("leads/",views.leads,name="leads"),path("leads/add/",views.lead_add,name="lead_add"),path("leads/<int:pk>/edit/",views.lead_edit,name="lead_edit"),path("leads/<int:pk>/delete/",views.lead_delete,name="lead_delete"),
 path("customers/",views.customers,name="customers"),path("customers/<int:pk>/",views.customer_detail,name="customer_detail"),path("followups/",views.followups,name="followups"),path("followups/add/",views.followup_add,name="followup_add"),path("followups/<int:pk>/complete/",views.followup_complete,name="followup_complete"),path("messages/",views.messages,name="messages"),path("messages/send/",views.message_send,name="message_send"),
 path("students/",lambda r:views.module_list(r,"students"),name="students"),path("students/add/",views.student_add,name="student_add"),path("students/<int:pk>/edit/",views.student_edit,name="student_edit"),path("students/<int:pk>/delete/",views.student_delete,name="student_delete"),
 path("courses/",lambda r:views.module_list(r,"courses"),name="courses"),path("courses/add/",views.course_add,name="course_add"),path("courses/<int:pk>/edit/",views.course_edit,name="course_edit"),path("courses/<int:pk>/delete/",views.course_delete,name="course_delete"),
 path("payments/",lambda r:views.module_list(r,"payments"),name="payments"),path("payments/add/",views.payment_add,name="payment_add"),path("payments/<int:pk>/edit/",views.payment_edit,name="payment_edit"),path("payments/<int:pk>/delete/",views.payment_delete,name="payment_delete"),
 path("tasks/",lambda r:views.module_list(r,"tasks"),name="tasks"),path("tasks/add/",views.task_add,name="task_add"),path("tasks/<int:pk>/edit/",views.task_edit,name="task_edit"),path("tasks/<int:pk>/delete/",views.task_delete,name="task_delete"),path("tasks/<int:pk>/toggle/",views.toggle_task,name="toggle_task"),
 path("marketing/",lambda r:views.module_list(r,"marketing"),name="marketing"),path("marketing/add/",views.campaign_add,name="campaign_add"),path("marketing/<int:pk>/edit/",views.campaign_edit,name="campaign_edit"),path("marketing/<int:pk>/delete/",views.campaign_delete,name="campaign_delete"),
 path("support/",lambda r:views.module_list(r,"support"),name="support"),path("support/add/",views.ticket_add,name="ticket_add"),path("support/<int:pk>/edit/",views.ticket_edit,name="ticket_edit"),path("support/<int:pk>/delete/",views.ticket_delete,name="ticket_delete"),
 path("reports/",views.reports,name="reports"),path("users/",views.users,name="users"),path("users/add/",views.user_add,name="user_add"),path("settings/",views.settings_page,name="settings"),path("pricing/",views.pricing,name="pricing"),path("role-dashboard/",views.role_dashboard,name="role_dashboard"),
 path("onboarding/<int:step>/",views.onboarding,name="onboarding_step"),path("onboarding/ready/",views.onboarding_ready,name="onboarding_ready"),path("exports/leads.csv",views.export_leads_csv,name="export_leads_csv"),path("exports/leads.xlsx",views.export_leads_xlsx,name="export_leads_xlsx"),path("exports/leads.pdf",views.export_leads_pdf,name="export_leads_pdf"),path("api/notifications/",views.api_notifications,name="api_notifications")]
